console.log('connected');


const allJobs = [
    {
        id: 1,
        title: "Mobile First Corp",
        profession: "React Native Developer",
        location: "Remote",
        time: "Full Time",
        salary: "$80,000 - $100,000",
        staus: "Not Applied",
        description: "We are looking for a skilled React Native Developer to join our team. The ideal candidate will have experience in building mobile applications using React Native and a strong understanding of mobile development best practices.",
    },
    {
        id: 2,
        title: "Pixel Perfect UI",
        profession: "Frontend Engineer",
        location: "New York, NY",
        time: "Full Time",
        salary: "$110,000 - $140,000",
        staus: "Not Applied",
        description: "Join our design-driven team to build stunning user interfaces. Proficiency in React, TypeScript, and Tailwind CSS is a must for this fast-paced role.",
    },
    {
        id: 3,
        title: "DataStream Systems",
        profession: "Backend Developer",
        location: "Austin, TX",
        time: "Full Time",
        salary: "$120,000 - $150,000",
        staus: "Not Applied",
        description: "We need a Node.js expert to scale our microservices architecture. You will be responsible for designing high-performance APIs and managing PostgreSQL databases.",
    },
    {
        id: 4,
        title: "CloudScale Solutions",
        profession: "DevOps Engineer",
        location: "Remote",
        time: "Contract",
        salary: "$90 - $120 / hr",
        staus: "Not Applied",
        description: "Help us automate our CI/CD pipelines and manage AWS infrastructure. Experience with Docker, Kubernetes, and Terraform is highly preferred.",
    },
    {
        id: 5,
        title: "Creative Pulse",
        profession: "UI/UX Designer",
        location: "London, UK",
        time: "Full Time",
        salary: "£55,000 - £75,000",
        staus: "Not Applied",
        description: "We are seeking a visionary designer to lead our product aesthetic. You'll conduct user research and create high-fidelity prototypes in Figma.",
    },
    {
        id: 6,
        title: "CyberShield AI",
        profession: "Security Analyst",
        location: "Washington, D.C.",
        time: "Full Time",
        salary: "$100,000 - $130,000",
        staus: "Not Applied",
        description: "Protect our clients' data by identifying vulnerabilities and implementing robust security protocols. Knowledge of SOC2 and penetration testing is key.",
    },
    {
        id: 7,
        title: "GreenTech Innovators",
        profession: "Full Stack Developer",
        location: "Berlin, DE",
        time: "Part Time",
        salary: "€40,000 - €50,000",
        staus: "Not Applied",
        description: "Work on sustainable energy solutions using the MERN stack. We value clean code, unit testing, and a passion for environmental impact.",
    },
    {
        id: 8,
        title: "Swift Logic",
        profession: "iOS Developer",
        location: "San Francisco, CA",
        time: "Full Time",
        salary: "$140,000 - $170,000",
        staus: "Not Applied",
        description: "Build the next generation of our consumer app using Swift and SwiftUI. You will collaborate closely with product managers to ship weekly updates.",
    },
];


